ALTER TABLE KSPL_LRNG_PLAN_ITEM ADD CATEGORY VARCHAR(255);

Alter table KSPL_LRNG_PLAN_ATTR add(TEMP_ATTR_VALUE CLOB);
UPDATE KSPL_LRNG_PLAN_ATTR SET ATTR_KEY_C = ATTR_VALUE;
COMMIT;
ALTER TABLE KSPL_LRNG_PLAN_ATTR DROP COLUMN ATTR_VALUE;
ALTER TABLE KSPL_LRNG_PLAN_ATTR RENAME COLUMN TEMP_ATTR_VALUE TO ATTR_VALUE;